Задание 1
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

если источник traffic_source равен yandex или google, то в source_type ставится organic
для источников paid и email из России - ставим ad
для источников paid и email не из России - ставим other
все остальные варианты берем из traffic_source без изменений

In [23]:
import pandas as pd

In [4]:
log = pd.read_csv('visit_log.csv',sep=';')

log.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [7]:
def source_type(row):
    traffic_source = row['traffic_source']
    region = row['region']
    if traffic_source == 'yandex' or traffic_source == 'google':
        return 'organic'  
    elif (traffic_source == 'paid' or traffic_source == 'email') and region == 'Russia':
        return 'ad'
    elif (traffic_source == 'paid' or traffic_source == 'email') and region != 'Russia':
        return 'other'

In [9]:
log['source_type'] = log.apply(source_type, axis=1)
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,None
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic

In [16]:
log.loc[log.source_type.isnull(), 'source_type'] = log['traffic_source']            #Заменяем None на значения столбца traffic_source
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic

Задание 2. В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

Прочитайте содержимое файла с датафрейм
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [31]:
import re

In [38]:
url = pd.read_csv('URLs.txt')
url.head(20)

                                                  url
0                                             /world/
1                                            /latest/
2                                       /?updated=top
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
8                                           /science/
9                                             /sport/
10  /middleeast/36131117-divizion-s-400-ne-zametil...
11  /economics/36065674-rossiyane-vozmutilis-minim...
12  /politics/36118047-otets-24-detey-potreboval-i...
13  /travel/36194479-v-sheremetevo-passazhiry-ustr...
14  /politics/35638742-nesolidno-mariya-zaharova-s...
15  /video/36012692-tramp-otkrestilsya-ot-rossii-i...
16     /starlife/36174817-guzeeva-rasstalas-s-muzhem/
17  /health/36149308-predlozheno-prostoe-sredstvo-...
18  /science/36139723-set-vzbudorazhila-novost-o-s...
19  /cis/36229699-poroshenko-obyavil-vseukrainskiy...

In [41]:
url[url.url.str.contains(r'/\d{8}-')].head(20)

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
10  /middleeast/36131117-divizion-s-400-ne-zametil...
11  /economics/36065674-rossiyane-vozmutilis-minim...
12  /politics/36118047-otets-24-detey-potreboval-i...
13  /travel/36194479-v-sheremetevo-passazhiry-ustr...
14  /politics/35638742-nesolidno-mariya-zaharova-s...
15  /video/36012692-tramp-otkrestilsya-ot-rossii-i...
16     /starlife/36174817-guzeeva-rasstalas-s-muzhem/
17  /health/36149308-predlozheno-prostoe-sredstvo-...
18  /science/36139723-set-vzbudorazhila-novost-o-s...
19  /cis/36229699-poroshenko-obyavil-vseukrainskiy...
20  /incidents/36225203-tonnel-obrushilsya-v-novoy...
21  /politics/36118047-otets-24-detey-potreboval-i...
22  /world/36075956-na-granitse-s-krymom-zahvachen...
23  /politics/36115220-mid-vystupil-s-preduprezhde...
24  /world/36018565-sbu-opublikovala-zapis-peregov...

Задание 3. 
В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [18]:
data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

In [17]:
from pymystem3 import Mystem

In [19]:
def make_lemmas(row):
    m = Mystem()
    search = row['keyword']
    lemma = m.lemmatize(search)
    lemma_1 = ' '.join(lemma).strip()
    return str(lemma_1)

In [20]:
data['lemmas'] = data.apply(make_lemmas, axis=1)
data.head()

                 keyword   shows                     lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль
1        доллары в рубли  114173         доллар   в   рубль
2  100 долларов в рублях   97534   100   доллар   в   рубль
3             курс рубля   53546               курс   рубль